### ISSUE TITLE
Signed Rosetta package is no longer signed

### ISSUE THREAD

**Issue by cgrohan** [grahampugh/Rosetta-2-install#3]
Hello and thank you for this code ! I need to use your Rosetta package signed in MDS for macOS deployment but your package is not signed anymore. Do you have time to re-sign and upload a new package ? Thx by advance :) Clément

**Comment by grahampugh** [comment]
Hi, the signing certificate expired. I have now re-signed it. Let me know if you continue to have problems.

**Comment by cgrohan** [comment]
> Hi, the signing certificate expired. I have now re-signed it. Let me know if you continue to have problems.

Thx ! I'll try now :)

**Comment by cgrohan** [comment]
The problem it's solved, thx again :)
